export default {
    CONTROL_PANEL: {
        USER_INFO_UPDATED: Symbol('USER_INFO_UPDATED'),
        USER_INFO_UPDATE_COMPLETED: Symbol('USER_INFO_UPDATE_COMPLETED'),
    },
    SCHEDULE: {
        SCHEDULE_CREATED_OR_DELETED: Symbol('SCHEDULE_CREATED_OR_DELETED'),
        SCHEDULE_MODIFIED: Symbol('SCHEDULE_MODIFIED'),
    },
};