import {PAGE_ID, PAGE_ID_TO_COMPONENT, PAGE_ID_TO_NAME, PAGE_ID_TO_ROUTE, PAGE_PREFIX, ROUTE_TO_PAGE_ID} from './PAGE';

export {
    PAGE_ID,
    PAGE_ID_TO_ROUTE,
    PAGE_ID_TO_COMPONENT,
    PAGE_ID_TO_NAME,
    ROUTE_TO_PAGE_ID,
    PAGE_PREFIX,
};