import {PAGE_ID} from './PAGE_ID';
import {PAGE_ID_TO_COMPONENT} from './PAGE_ID_TO_COMPONENT';
import {PAGE_ID_TO_NAME} from './PAGE_ID_TO_NAME';
import {PAGE_ID_TO_ROUTE, PAGE_PREFIX} from './PAGE_ID_TO_ROUTE';
import {ROUTE_TO_PAGE_ID} from './ROUTE_TO_PAGE_ID';

export {
    PAGE_ID,
    PAGE_ID_TO_COMPONENT,
    PAGE_ID_TO_NAME,
    PAGE_ID_TO_ROUTE,
    ROUTE_TO_PAGE_ID,
    PAGE_PREFIX,
};