import {PAGE_ID} from '../PAGE';

export const PAGE_PREFIX = {
    INDEX: '/',
    ACCOUNT: '/account',
    CONTROL_PANEL: '/controlPanel',
};

export const PAGE_ID_TO_ROUTE = {
    [PAGE_ID.INDEX]: '/',

    [PAGE_ID.ACCOUNT.LOGIN]: `${PAGE_PREFIX.ACCOUNT}/login`,
    [PAGE_ID.ACCOUNT.SIGN_UP]: `${PAGE_PREFIX.ACCOUNT}/signUp`,
    [PAGE_ID.ACCOUNT.RETRIEVE_PASSWORD]: `${PAGE_PREFIX.ACCOUNT}/retrievePassword`,

    [PAGE_ID.CONTROL_PANEL.SCHEDULE]: `${PAGE_PREFIX.CONTROL_PANEL}/schedule`,
    [PAGE_ID.CONTROL_PANEL.NEW_PROJECT]: `${PAGE_PREFIX.CONTROL_PANEL}/newProject`,
    [PAGE_ID.CONTROL_PANEL.MY_PROJECT]: `${PAGE_PREFIX.CONTROL_PANEL}/myProject`,
    [PAGE_ID.CONTROL_PANEL.PROJECT_DETAIL]: `${PAGE_PREFIX.CONTROL_PANEL}/projectDetail`,
    [PAGE_ID.CONTROL_PANEL.FRIEND_LIST]: `${PAGE_PREFIX.CONTROL_PANEL}/friendList`,
    [PAGE_ID.CONTROL_PANEL.ACCOUNT_MANAGEMENT]: `${PAGE_PREFIX.CONTROL_PANEL}/accountManagement`,
};