const INDEX = 'INDEX';

const ACCOUNT = {
    LOGIN: 'LOGIN',
    SIGN_UP: 'SIGN_UP',
    RETRIEVE_PASSWORD: 'RETRIEVE_PASSWORD',
};

const CONTROL_PANEL = {
    NEW_SCHEDULE: 'NEW_SCHEDULE',
    NEW_PROJECT: 'NEW_PROJECT',
    MY_PROJECT: 'MY_PROJECT',
    PROJECT_DETAIL: 'PROJECT_DETAIL',
    FRIEND_LIST: 'FRIEND_LIST',
    ACCOUNT_MANAGEMENT: 'ACCOUNT_MANAGEMENT',
};

export const PAGE_ID = {
    INDEX,
    ACCOUNT,
    CONTROL_PANEL,
};