import {PAGE_ID} from '../PAGE';

const PREFIX = {
    ACCOUNT: '/account',
    CONTROL_PANEL: '/controlPanel',
};

export const PAGE_ID_TO_ROUTE = {
    [PAGE_ID.INDEX]: '/',

    [PAGE_ID.ACCOUNT.LOGIN]: `${PREFIX.ACCOUNT}/login`,
    [PAGE_ID.ACCOUNT.SIGN_UP]: `${PREFIX.ACCOUNT}/signUp`,
    [PAGE_ID.ACCOUNT.RETRIEVE_PASSWORD]: `${PREFIX.ACCOUNT}/retrievePassword`,

    [PAGE_ID.CONTROL_PANEL.NEW_SCHEDULE]: `${PREFIX.CONTROL_PANEL}/newSchedule`,
    [PAGE_ID.CONTROL_PANEL.NEW_PROJECT]: `${PREFIX.CONTROL_PANEL}/newProject`,
    [PAGE_ID.CONTROL_PANEL.MY_PROJECT]: `${PREFIX.CONTROL_PANEL}/myProject`,
    [PAGE_ID.CONTROL_PANEL.PROJECT_DETAIL]: `${PREFIX.CONTROL_PANEL}/projectDetail`,
    [PAGE_ID.CONTROL_PANEL.FRIEND_LIST]: `${PREFIX.CONTROL_PANEL}/friendList`,
    [PAGE_ID.CONTROL_PANEL.ACCOUNT_MANAGEMENT]: `${PREFIX.CONTROL_PANEL}/accountManagement`,
};